### DISCUSSION TITLE
Netlify CMS config.yml sample

### DISCUSSION THREAD

**Discussion by vasfvitor** [Vagr9K/gatsby-advanced-starter#162] [Show and tell]
I'm very new to gatsby, JS and dev in general, with that in mind:

I'm working on a config.yml file for Netlify CMS to create blog posts based on what this starter needs to create the post, so far this model is working in localhost, I tried to deploy to Netlify but the build failed (non related to this file).

All this was made possible by the docs in [netlifycms.org](https://www.netlifycms.org/)

config.yml
```
backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: your-user/gatsby-advanced-starter # Repo for pushing new commits. Make sure to replace with your repo!

commit_messages:        #I copied this section from a Netlify CMS demo
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: "content/images"     #absolute project path. Probably ContentDir/images
public_folder: "images"     #path that will be parsed to .md file (following the .mdx default post structure)
# publish_mode: editorial_workflow   #enable the flow: draft -> in review -> ready (published) You can remove this line if you think it slowdown your work

collections: #option in the CMS panel
  - name: "post"
    label: "Blog Post"
    folder: "content" # posts output folder (.md filetype)
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # filename format
    fields:
      - {label: "Title", name: "title", widget: "string"}               
      - {label: "Cover", name: "cover", widget: image}
      - {label: "coverAlt", name: coverAlt, widget: "string"} 
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: 'Category', name: 'category' ,widget: 'string'}
      - {label: 'tags', name: 'tags', widget: 'list' }
      - {label: "Publish Date", name: "datePublished", widget: "datetime" }
      - {label: "Date Modified", name: "dateModified", widget: "datetime"}
```

The folders needs to be adjusted per project. The Gatsby Advanced Starter uses the path `images` to build the posts, so `public_folder` path must remain unchanged.
